### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by EmanuelLoos** [divinsmathew/echo#1]
If this is a free software project, as in freedom, not money, or an open source project if you prefer that term (free software is about ethics, Open Source software is legally almost equivalent but is not about ethics, it is what the large companies do) it needs a license so it is legal to use your app and so that contributing legally works in a way that makes sense.

I highly recommend the GNU General Public License, version 3, with the or-later clause defined in the copyright & license notice. It would also be good to include the short notice as a comment at the top of every file that is part of the code.

The GPLv3-or-later is a strong copyleft license. It grants the four essential freedoms of free software and protects your code from being stolen and sold as part of non-free software which does not grant those freedoms. At the same time it allows healthy cooperation with other free software projects by letting them use your code in their project if theirs licensed under the terms of the same or a compatible license (meaning you can do the same with their work) if they attribute you as the author of the parts that are from you.

If you would like to use a weeker license that also allows your code to be used in non-free software I wold recommend the Apache License, version 2.

But before being open to contributions legally makes sense your project needs a license.

**Comment by divinsmathew** [comment]
Done.
